# Dependencies
markdown:         redcarpet
# pygments:         true
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            lxxxc
tagline:          ''
description:      'Talk is cheap, show me the work!'
url:              https://lxxxc.github.io/

author:
  name:           'lxxxc'
  url:            https://lxxxc.github.io/

paginate:         5


github:
  repo:           https://github.com/lxxxc
