# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            lxxxc
tagline:          ''
description:      'Talk is cheap, show me the work!'
url:              https://lxxxc.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5


github:
  repo:           https://lxxxc.github.io/
